version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: novo_rio
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: novo_rio_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
