version: '3.8'

services:
  backend:
    image: novo-rio-backend
    ports:
      - "8084:8084"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/novo_rio
      - PYTHONPATH=/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=novo_rio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
